"""
Streamlit demo for FactCheck-Lite.

Run with:  streamlit run app.py
"""
import streamlit as st
from src.checker import FactConsistencyChecker

st.set_page_config(page_title="FactCheck-Lite", page_icon="🔍")

st.title("🔍 FactCheck-Lite")
st.caption("Hallucination / factual-consistency checker using zero-shot NLI")

st.markdown(
    "Paste a **source document** (e.g. retrieved context, ground truth) and "
    "a **claim** (e.g. a sentence generated by an LLM). The tool checks "
    "whether the claim is actually supported by the source."
)

with st.form("check_form"):
    source = st.text_area(
        "Source document",
        value="The Eiffel Tower was completed in 1889 and is located in Paris, France.",
        height=100,
    )
    claim = st.text_area(
        "Claim to verify",
        value="The Eiffel Tower was built in London in 1920.",
        height=80,
    )
    submitted = st.form_submit_button("Check consistency")

if submitted:
    with st.spinner("Analyzing..."):
        checker = FactConsistencyChecker(prefer_transformer=True)
        result = checker.check(source, claim)

    color = {
        "SUPPORTED": "green",
        "CONTRADICTED": "red",
        "UNVERIFIABLE": "orange",
    }[result.label]

    st.markdown(f"### Result: :{color}[{result.label}]")
    st.progress(result.confidence)
    st.caption(f"Confidence: {result.confidence} · Method: {result.method}")

    if result.method == "tfidf-fallback":
        st.info(
            "Running on the lightweight TF-IDF fallback (no internet access "
            "to download the transformer model). Results will be more "
            "accurate once run with an internet connection, which downloads "
            "the real NLI model automatically."
        )

st.divider()
st.caption(
    "Built as part of exploring NLP applications for hallucination detection. "
    "Primary method: zero-shot NLI via facebook/bart-large-mnli."
)
